export const tableContent = [ 
    {
        col1:"gxt_8pbucf_0a_8PBUCF_M4P_1AA.oas",
        status:"green",
        col2:"TapeOutlog_date1.log"
    },
    {
        col1:"gxt_8pbucf_0a_8PBUCF_M4P_2AA.oas",
        status:"green",
        col2:"TapeOutlog_date.log" 
    },
    {
        col1:"gxt_8pbucf_0a_8PBUCF_M4G_1AA.oas",
        status:"green",
        col2:"TapeOutlog4_date.log" 
    },
    {
        col1:"gxt_8pbucf_0a_8PBUCF_M4G_1AA.oas",
        status:"green",
        col2:"TapeOutlog3_date.log" 
    },
    {
        col1:"gxt_8pbucf_1a_8PBUCF_M4P_2AA.oas",
        status:"red",
        col2:"TapeOutlog_4date.log" 
    },
    {
        col1:"gxt_8pbucf_01_8PBUCF_M4P_3AA.oas",
        status:"green",
        col2:"TapeOutlog3_date.log" 
    },
    {
        col1:"gxt_8pbucf_2a_8PBUCF_M4P_4AA.oas",
        status:"green",
        col2:"TapeOutlog1_date.log" 
    },
    {
        col1:"gxt_8pbucf_01_8PBUCF_M4P_3AA.oas",
        status:"green",
        col2:"TapeOutlog3_date.log" 
    },
    {
        col1:"gxt_8pbucf_01_8PBUCF_M4G_3AA.oas",
        status:"green",
        col2:"TapeOutlog3_date.log" 
    },
    {
        col1:"gxt_8pbucf_01_8PBUCF_M4G_3AA.oas",
        status:"green",
        col2:"TapeOutlog3_date.log" 
    },
];